[project]
name = "udi-training-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.2.3",
    "udi-grammar-py>=0.2.0",
]
